# -*- coding: utf-8 -*-
{
    'name': 'CaDiffusion Base',
    'version': '19.0.1.0.0',
    'summary': 'Champs et vues personnalisés Cadiffusion (migration depuis Studio)',
    'category': 'Custom',
    'author': 'Cadiffusion',
    'depends': [
        'base',
        'mail',
        'sale_management',
        'purchase',
        'account',
        'stock',
        'mrp',
        'product',
        'public_tender',
        'account_followup',
        'margin',
        'account_invoice_transmit_method',
        'l10n_fr_chorus_account',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/fix_stale_data.xml',
        'views/account_move_views.xml',
        'views/mrp_production_views.xml',
        'views/product_views.xml',
        'views/purchase_order_views.xml',
        'views/res_partner_views.xml',
        'views/sale_order_views.xml',
        'views/stock_views.xml',
        'views/tender_order_views.xml',
    ],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
