{
    'name': 'CaDiffusion Base',
    'version': '19.0.1.0.21',
    'summary': 'Champs et vues personnalisés Cadiffusion (migration depuis Studio)',
    'category': 'Custom',
    'author': 'Cadiffusion',
    'depends': [
        'base',
        'mail',
        'sale_management',
        'purchase',
        'account',
        'stock',
        'sale_stock',
        # stock.move.purchase_line_id, utilisé par _compute_packaging_uom_id
        'purchase_stock',
        'stock_delivery',
        'mrp',
        'product',
        'buying_price',
        'public_tender',
        'account_followup',
        'margin',
        'account_payment_mode',
        'account_invoice_transmit_method',
        'account_invoice_facturx',
        # writer PDF natif + template XMP utilisés par _chorus_embed_facturx_xml
        'account_edi_ubl_cii',
        'l10n_fr_chorus_account',
        # l'override de _chorus_get_invoice (account_move.py) doit charger
        # APRÈS l10n_fr_chorus_facturx pour l'envelopper dans le MRO
        'l10n_fr_chorus_facturx',
        'l10n_fr_facturx_chorus_pro',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/fix_stale_data.xml',
        'data/core_view_activation.xml',
        'views/account_move_views.xml',
        'views/mrp_production_views.xml',
        'views/product_views.xml',
        'views/purchase_order_views.xml',
        'views/res_partner_views.xml',
        'views/sale_order_views.xml',
        'views/stock_views.xml',
        'views/tender_order_views.xml',
        'views/misc_views.xml',
        'views/studio_post_upgrade_views.xml',
        'report/mrp_production_report.xml',
    ],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
    'post_init_hook': 'post_init_hook',
}
