from datetime import date

from odoo import Command
from odoo.tests import common


class TestTenderConfirm(common.TransactionCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        # Customer pricelists coming from the legacy database are shared
        # between companies (no company set).
        cls.customer_pricelist = cls.env["product.pricelist"].create(
            {"name": "Customer shared pricelist", "company_id": False}
        )
        cls.customer = cls.env["res.partner"].create(
            {
                "name": "Tender customer",
                "property_product_pricelist": cls.customer_pricelist.id,
            }
        )
        cls.public_customer = cls.env["res.partner"].create(
            {"name": "Public pricelist customer"}
        )
        cls.public_customer.property_product_pricelist = cls.env[
            "product.pricelist"
        ].browse(1)
        cls.product = cls.env["product.product"].create(
            {"name": "Tender product", "sale_ok": True, "list_price": 10.0}
        )
        cls.tender = cls.env["tender.order"].create(
            {
                "name": "Tender shared pricelists",
                "start_date": date(2026, 8, 11),
                "end_date": date(2027, 7, 1),
                "partner_ids": [
                    Command.set([cls.customer.id, cls.public_customer.id])
                ],
                "tender_price_lines": [
                    Command.create(
                        {"product_id": cls.product.id, "revision_price": 0.5}
                    )
                ],
            }
        )

    def test_confirm_creates_shared_pricelists(self):
        self.tender.action_confirm()

        self.assertEqual(self.tender.state, "confirm")
        tender_pricelist = self.tender.tender_pricelist_id
        self.assertTrue(tender_pricelist)
        self.assertFalse(
            tender_pricelist.company_id,
            "The tender pricelist must stay shared between companies",
        )
        self.assertEqual(tender_pricelist.item_ids.product_tmpl_id, self.product.product_tmpl_id)
        self.assertEqual(tender_pricelist.item_ids.fixed_price, 0.5)

        customer_items = self.customer_pricelist.item_ids.filtered(
            lambda pricelist_item: pricelist_item.base_pricelist_id == tender_pricelist
        )
        self.assertEqual(len(customer_items), 1)
        self.assertFalse(customer_items.company_id)

        generated_pricelist = self.public_customer.property_product_pricelist
        self.assertNotEqual(generated_pricelist.id, 1)
        self.assertFalse(
            generated_pricelist.company_id,
            "The customer pricelist generated by the tender must stay shared",
        )
        self.assertEqual(
            generated_pricelist.item_ids.base_pricelist_id, tender_pricelist
        )
