from . import account_move
from . import account_edi_xml_ubl_bis3
from . import ca_diffusion_preparer
from . import ir_actions_report
from . import mrp_production
from . import product_pricelist
from . import product_supplierinfo
from . import product_template
from . import purchase_order
from . import res_partner
from . import sale_order
from . import stock
from . import tender_order
from . import reference_state
