# Copyright 2017-2020 Akretion (http://www.akretion.com)
# @author: Alexis de Lattre <alexis.delattre@akretion.com>
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

from io import BytesIO

from odoo import models
from odoo.exceptions import UserError

try:
    from facturx import get_facturx_xml_from_pdf
except ImportError:
    get_facturx_xml_from_pdf = None


class AccountMove(models.Model):
    _inherit = "account.move"

    def _cii_trade_contact_department_name(self, partner):
        # Only add chorus service department for the buyer contact (BT-56).
        # Applying it to the seller contact (BT-41) is semantically wrong and
        # triggers CII-SR-465: PersonName and DepartmentName are mutually
        # exclusive — you cannot have both in the same DefinedTradeContact.
        if partner != self.partner_id:
            return super()._cii_trade_contact_department_name(partner)
        chorus_service = self._get_chorus_service()
        if chorus_service:
            return chorus_service.name or partner.name
        return super()._cii_trade_contact_department_name(partner)

    def _cii_trade_agreement_buyer_ref(self, partner):
        chorus_service = self._get_chorus_service()
        if chorus_service:
            return chorus_service.code
        return super()._cii_trade_agreement_buyer_ref(partner)

    def _chorus_get_invoice(self, chorus_invoice_format):
        self.ensure_one()
        if chorus_invoice_format == "xml_cii":
            chorus_file_content = self.with_context(
                fr_chorus_cii16b=True
            ).generate_facturx_xml()[0]
        elif chorus_invoice_format == "pdf_factur-x":
            # Reference the report action by xmlid, not by report_name:
            # report_cadiffusion redirects account.account_invoices to its own
            # template, so no ir.actions.report carries the report_name
            # 'account.report_invoice_with_payments' and v19 _get_report()
            # raises instead of falling back. The Factur-X XML is embedded
            # during rendering by account_invoice_facturx
            # (_render_qweb_pdf_prepare_streams), whatever the template.
            # no_embedded_factur-x_xml=False re-enables that embedding, which
            # cadiffusion_base disables globally for interactive prints:
            # Chorus requires the XML inside the PDF for this flow format.
            chorus_file_content, filetype = (
                self.env["ir.actions.report"]
                .with_context(**{"no_embedded_factur-x_xml": False})
                ._render("account.account_invoices", [self.id])
            )
            assert filetype == "pdf", "wrong filetype"
            self._chorus_check_facturx_xml_embedded(chorus_file_content)
        else:
            chorus_file_content = super()._chorus_get_invoice(chorus_invoice_format)
        return chorus_file_content

    def _chorus_check_facturx_xml_embedded(self, pdf_content):
        """Chorus Pro rejects a pdf_factur-x flow whose PDF has no embedded
        factur-x.xml. The embedding can be skipped silently (facturx lib
        missing, or the defensive wrapper of cadiffusion_base swallowing an
        embed failure), so fail loudly here instead of at Chorus."""
        self.ensure_one()
        xml_filename = None
        if get_facturx_xml_from_pdf is not None:
            # check_xsd=False: the XML was already XSD-validated when it was
            # generated by generate_facturx_xml()
            xml_filename = get_facturx_xml_from_pdf(
                BytesIO(pdf_content), check_xsd=False
            )[0]
        if not xml_filename:
            raise UserError(
                self.env._(
                    "The PDF generated for invoice %s does not contain the "
                    "embedded Factur-X XML file required by Chorus Pro. "
                    "The Factur-X embedding failed or was skipped — check "
                    "the server logs.",
                    self.display_name,
                )
            )

    def _prepare_facturx_attachments(self):
        res = super()._prepare_facturx_attachments()
        for attach in self.chorus_attachment_ids:
            res[attach.name] = {
                "filedata": attach.raw,
                "modification_datetime": attach.write_date,
                "creation_datetime": attach.create_date,
            }
        return res
